### ISSUE TITLE
Why do I get this error?

### ISSUE THREAD

**Issue by Michuk02** [posit-dev/shinylive#149]
I try to run this working Shiny app on Shinylive, but for some reason conversion is not working i have been stuck on this for hours and I ran out of ideas, could anyone please help? 

install.packages("ggplot2")
library(shiny)
library(pwr)
library(ggplot2)

# Define UI for application
ui <- fluidPage(
  titlePanel("Sample Size Calculator for Correlation"),
  sidebarLayout(
    sidebarPanel(
      numericInput("correlation", "Expected Correlation Coefficient:", value = 0.5, min = 0, max = 1, step = 0.01),
      numericInput("power", "Desired Power (e.g., 0.80):", value = 0.80, min = 0, max = 1, step = 0.01),
      numericInput("alpha", "Significance Level (e.g., 0.05):", value = 0.05, min = 0, max = 1, step = 0.01),
      actionButton("calculate", "Calculate Sample Size")
    ),
    mainPanel(
      textOutput("result"),
      plotOutput("powerPlot")
    )
  )
)

# Define server logic required to calculate sample size and render plot
server <- function(input, output) {
  observeEvent(input$calculate, {
    correlation <- input$correlation
    power <- input$power
    alpha <- input$alpha
    
    result <- pwr.r.test(r = correlation, power = power, sig.level = alpha)
    
    output$result <- renderText({
      paste("Required Sample Size:", ceiling(result$n))
    })
    
    output$powerPlot <- renderPlot({
      sample_sizes <- seq(5, 50, by = 1)
      power_values <- sapply(sample_sizes, function(n) {
        pwr.r.test(n = n, r = correlation, sig.level = alpha)$power
      })
      
      plot_data <- data.frame(
        sample_size = sample_sizes,
        power = power_values
      )
      
      ggplot(plot_data, aes(x = sample_size, y = power)) +
        geom_line(color = "red") +
        geom_point() +
        geom_vline(xintercept = ceiling(result$n), linetype = "dashed", color = "blue") +
        annotate("text", x = ceiling(result$n), y = 0.1, label = paste("optimal sample size\nn =", ceiling(result$n)), color = "blue", angle = 90, vjust = -0.5) +
        labs(
          title = "Proportion Power Calculation for Binomial Distribution (Arcsine Transformation)",
          x = "Sample Size",
          y = "Test Power = 1 - β"
        ) +
        theme_minimal()
    })
  })
}

shinyApp(ui = ui, server = server)

shinylive::export(appdir = "code", destdir = "docs")

httpuv::runStaticServer("docs")

And the error i get, when inspecting the opening website is like this: 
Uncaught (in promise) Error: Unexpected response type: "null", expected "list".
    at handleHttpuvRequests (shinylive.js:32135:17)
    at async makeHttpuvRequest (shinylive.js:32091:3)
    at async WebRWorkerProxy.makeRequest (shinylive.js:33584:5)

**Comment by gadenbuie** [comment]
Hi @Michuk02. I've tried using your example, but I can't reproduce the issue. For me, the app works as expected when I export it, using both the CRAN and dev versions of `shinylive` (the R package). I also was able to run your example [on shinylive.io](https://shinylive.io/r/editor/#code=NobwRAdghgtgpmAXGKAHVA6ASmANGAYwHsIAXOMpMAGwEsAjAJykYE8AKAZwAtaJWAlAB0IdJiw6oA7o2GiGzNuwDmy1NSKkATHJEBiAAQAROADM+cAwFUAkgdNFGBtOtoEopWiREBXWgYAeAFp7aj8AEwAFKGU4dhEDA09SajhoiDhqeLAAZVh1SxzaAC9LAGEoagIfag9He3qyx0ZMjy8IITABXASDTlpwuHoWABkoViIfUniIRMT+weHGdMyZubmIH3hGNxsIVCns4kYW2s9vPANOgFEAD1Q4AnJwgyaT1vPZprNzAloKUiITq4AwAN0qPksAF4DAAGDAAVhBMD4BhhsORUFuaIMAEYQZxyKgcfDYbjur11pttrt9odOqgiFI4IxgVcwCZ+i0XpEmSyDOw4BhlBgQfCABywgRAy7gsLQuEYSXI1HozHYmH4vpEkkYMkU2brAzUlm0g7TTqVVDcKBszpFZQQWi-KAQAiWEZwUGZAVCkVivUI6VsuWQ3WwpEGFGzNVRrE4rWEuDE9F68k9Q3rKBPdoAISmpBIR0q1TOcDtYAqVRqHkK+VSBiKpU6cnWBvWMCgfBWWUpc3It1IAHkpubsi1ODVSC2M0aDOpNCPSGOGXzlhpp10+62DHJdBBDCZzBk+izvU4NMo3AYWgBHPzcpJEAzuatlvr1yz9UrOCAvFp-vyC7ThAnBnvywT2D4bqfOwfDmiCkzLlMAgGCAvREPQYGMN61zemQcF0qQAAkr6lrWILoZmL7NB87SBCE8FTKRtFnO0faMsyTiQUxJGcSyfZWjaDEGLxxFCba1F9hOU4idIjAYAp5CEuwTgwscpxtCQIL8Wp85rgStAiqk3rUDiEk7okfZIeaxEydQpAiQBgyMAAKnAg7sFRc6oFASbZFgcD3rQj55DABSNiUcAyiC7q0HQEDKKpcCTg5xEQAIlkGAAvll1mjsxumRBuTkUC5xWaF5fbzJ+AD634pSJYG3uwkYIhiBj0KwCZZYkum1aGjWQZwLjUBwI3hak9VRZwIKmNBOZFhlaHVXM8mKRgynTDGxognpGl0dpfRGRgJk+jCFnEbpq25atq3AbV4QeFAIlPaQUAYKYzDwGsc4fpNcDTT+MITQUQMpbOf26Ti-WDZwq29Vc1GJKowHsA9b1QCCUApewGr-WDDUgt1MK6ZlBgANSrSjcBEDAtUJXExAaHpnTci2lPUwYsR07VjJ8NMqFU8jcw8-ToKM3jAssu6qCOepcDxXwSX2SRGUgozpCsA8OKdE9PBwOEbLM-UMKdPQ8oc8Lf2-hAmi1tkA6biC+NxQlKspVO6XdAYJOKlqtT0Od85+eQ2REHLtCdmZoMNg1QgiDGxuK+7yWpWrmWxUQLO62AFuQmyrrKA2MIAJwdaCABWPiEjiQTwkGnMi4kgecL9NvJCX7KRIwEeOJ8Bi8lxrwljWA8OE4uZ8HTtCVMYtCEjs9BTPR7AAIKMAQ-Qnq5zCgRPnafMIeBc4k+P2p+kXNifzdzH7nTubXQ-8pqBghIATcCdFzQtc6Q3BwPAWq0Yo6VHYFlW6hoIHZRECIHgfBWBr3QOwPwOI-AEnAnpbC54BBgGygAXSAA).

Can you confirm that your app is located in `code/app.R`? Are `code/` and `docs/` the actual app and export locations on your computer, or were they something you changed for the example?

**Comment by Michuk02** [comment]
Yes, they are the locations of both app and export, if it works for you its even weirder than i thought.

**Comment by gadenbuie** [comment]
Can you share the output of both `devtools::session_info()` and `shinylive::assets_info()`?

**Comment by Michuk02** [comment]
Session info ────────────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value
 version  R version 4.4.1 (2024-06-14 ucrt)
 os       Windows 10 x64 (build 19045)
 system   x86_64, mingw32
 ui       RStudio
 language (EN)
 collate  Polish_Poland.utf8
 ctype    Polish_Poland.utf8
 tz       Europe/Warsaw
 date     2024-07-08
 rstudio  2024.04.2+764 Chocolate Cosmos (desktop)
 pandoc   NA

─ Packages ────────────────────────────────────────────────────────────────────────────────────────────────────────────
 ! package     * version date (UTC) lib source
 D archive       1.1.8   2024-04-28 [1] CRAN (R 4.4.1)
   brio          1.1.5   2024-04-24 [1] CRAN (R 4.4.1)
   bslib         0.7.0   2024-03-29 [1] CRAN (R 4.4.1)
   cachem        1.1.0   2024-05-16 [1] CRAN (R 4.4.1)
   cli           3.6.3   2024-06-21 [1] CRAN (R 4.4.1)
   colorspace    2.1-0   2023-01-23 [1] CRAN (R 4.4.1)
   crayon        1.5.3   2024-06-20 [1] CRAN (R 4.4.1)
   curl          5.2.1   2024-03-01 [1] CRAN (R 4.4.1)
   devtools      2.4.5   2022-10-11 [1] CRAN (R 4.4.1)
   digest        0.6.36  2024-06-23 [1] CRAN (R 4.4.1)
   dplyr       * 1.1.4   2023-11-17 [1] CRAN (R 4.4.1)
   ellipsis      0.3.2   2021-04-29 [1] CRAN (R 4.4.1)
   fansi         1.0.6   2023-12-08 [1] CRAN (R 4.4.1)
   fastmap       1.2.0   2024-05-15 [1] CRAN (R 4.4.1)
   fs            1.6.4   2024-04-25 [1] CRAN (R 4.4.1)
   generics      0.1.3   2022-07-05 [1] CRAN (R 4.4.1)
   ggplot2     * 3.5.1   2024-04-23 [1] CRAN (R 4.4.1)
   glue          1.7.0   2024-01-09 [1] CRAN (R 4.4.1)
   gtable        0.3.5   2024-04-22 [1] CRAN (R 4.4.1)
   hms           1.1.3   2023-03-21 [1] CRAN (R 4.4.1)
   htmltools     0.5.8.1 2024-04-04 [1] CRAN (R 4.4.1)
   htmlwidgets   1.6.4   2023-12-06 [1] CRAN (R 4.4.1)
   httpuv        1.6.15  2024-03-26 [1] CRAN (R 4.4.1)
   httr2         1.0.1   2024-04-01 [1] CRAN (R 4.4.1)
   jquerylib     0.1.4   2021-04-26 [1] CRAN (R 4.4.1)
   jsonlite      1.8.8   2023-12-04 [1] CRAN (R 4.4.1)
   later         1.3.2   2023-12-06 [1] CRAN (R 4.4.1)
   lifecycle     1.0.4   2023-11-07 [1] CRAN (R 4.4.1)
   magrittr      2.0.3   2022-03-30 [1] CRAN (R 4.4.1)
   memoise       2.0.1   2021-11-26 [1] CRAN (R 4.4.1)
   mime          0.12    2021-09-28 [1] CRAN (R 4.4.0)
   miniUI        0.1.1.1 2018-05-18 [1] CRAN (R 4.4.1)
   munsell       0.5.1   2024-04-01 [1] CRAN (R 4.4.1)
   pillar        1.9.0   2023-03-22 [1] CRAN (R 4.4.1)
   pkgbuild      1.4.4   2024-03-17 [1] CRAN (R 4.4.1)
   pkgconfig     2.0.3   2019-09-22 [1] CRAN (R 4.4.1)
   pkgload       1.4.0   2024-06-28 [1] CRAN (R 4.4.1)
   prettyunits   1.2.0   2023-09-24 [1] CRAN (R 4.4.1)
   profvis       0.3.8   2023-05-02 [1] CRAN (R 4.4.1)
   progress      1.2.3   2023-12-06 [1] CRAN (R 4.4.1)
   promises      1.3.0   2024-04-05 [1] CRAN (R 4.4.1)
   purrr         1.0.2   2023-08-10 [1] CRAN (R 4.4.1)
   pwr         * 1.3-0   2020-03-17 [1] CRAN (R 4.4.1)
   R6            2.5.1   2021-08-19 [1] CRAN (R 4.4.1)
   rappdirs      0.3.3   2021-01-31 [1] CRAN (R 4.4.1)
   Rcpp          1.0.12  2024-01-09 [1] CRAN (R 4.4.1)
   remotes       2.5.0   2024-03-17 [1] CRAN (R 4.4.1)
   rlang         1.1.4   2024-06-04 [1] CRAN (R 4.4.1)
   sass          0.4.9   2024-03-15 [1] CRAN (R 4.4.1)
   scales        1.3.0   2023-11-28 [1] CRAN (R 4.4.1)
   sessioninfo   1.2.2   2021-12-06 [1] CRAN (R 4.4.1)
   shiny       * 1.8.1.1 2024-04-02 [1] CRAN (R 4.4.1)
   shinylive     0.1.1   2023-12-04 [1] CRAN (R 4.4.1)
   stringi       1.8.4   2024-05-06 [1] CRAN (R 4.4.0)
   stringr       1.5.1   2023-11-14 [1] CRAN (R 4.4.1)
   tibble        3.2.1   2023-03-20 [1] CRAN (R 4.4.1)
   tidyselect    1.2.1   2024-03-11 [1] CRAN (R 4.4.1)
   urlchecker    1.0.1   2021-11-30 [1] CRAN (R 4.4.1)
   usethis       2.2.3   2024-02-19 [1] CRAN (R 4.4.1)
   utf8          1.2.4   2023-10-22 [1] CRAN (R 4.4.1)
   vctrs         0.6.5   2023-12-01 [1] CRAN (R 4.4.1)
   withr         3.0.0   2024-01-16 [1] CRAN (R 4.4.1)
   xtable        1.8-4   2019-04-21 [1] CRAN (R 4.4.1)

 [1] C:/Users/Michał/AppData/Local/R/win-library/4.4
 [2] C:/Program Files/R/R-4.4.1/library

 D ── DLL MD5 mismatch, broken installation.


shinylive R package version:  0.1.1
shinylive web assets version: 0.2.3

Local cached shinylive asset dir:
    C:\Users\Michał\AppData\Local\shinylive\shinylive\Cache

Installed assets:
    C:/Users/Michał/AppData/Local/shinylive/shinylive/Cache/shinylive-0.2.3

**Comment by Michuk02** [comment]
Any other ideas?

**Comment by Michuk02** [comment]
OK, the issue now changed to this: 
preload error:wasm streaming compile failed: TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'.
